### ISSUE TITLE
Implement ES6 export file

### ISSUE THREAD

**Issue by julmot** [apollographql/graphql-tag#303]
Angular worked on the build process in v10 and removed support for already transpiled code to ES5 for Angular Libraries. Also they now show a warning for every dependency that is imported in ES5.

More information:
https://angular.io/guide/build#configuring-commonjs-dependencies

Example warning:

```
WARNING in P:\XXX\XXX.js depends on graphql-tag. CommonJS or AMD
 dependencies can cause optimization bailouts.
```

To avoid this we'd need an ES6 file in "main" property of package.json or at least a file in the `lib` folder in ES6 that can be imported directly. This should be the feature request of this issue.

**Comment by MatthiasKunnen** [comment]
Seems like #273 should fix this although it's an old PR.

**Comment by nikita-lobkov** [comment]
@MatthiasKunnen 
Any updates for this?

**Comment by MatthiasKunnen** [comment]
@nikita-lobkov, you should check the linked PRs for progress. None of these are mine so I'm afraid I can't give you an update.

**Comment by xino1010** [comment]
on Angular v10 to remove all warnings:

File angular.json

"architect": {
        "build": {
            "options": {
                 "allowedCommonJsDependencies": [
                     "graphql-tag",
                     "zen-observable"
                 ]
            }
         }
}

**Comment by rajinder-yadav** [comment]
It's 2021 and I am still see this warning? along with another for Observable.

```
Warning: /home/yadav/home/yadav/projects/websites/devmentor/node_modules/@apollo/client/core/index.js depends on 'graphql-tag'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /home/yadav/home/yadav/projects/websites/devmentor/node_modules/@apollo/client/utilities/observables/Observable.js depends on 'zen-observable'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by youssefkrio** [comment]
i am still getting the same issue

**Comment by pawelpiotrowski** [comment]
Same here:
```
Warning: .../node_modules/@apollo/client/utilities/observables/Observable.js depends on 'zen-observable'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
Package:
```
"dependencies": {
    "@angular/animations": "~11.2.0",
    "@angular/cdk": "^11.2.0",
    "@angular/common": "~11.2.0",
    "@angular/compiler": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "~11.2.0",
    "@angular/material": "^11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "apollo-angular": "^2.4.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3",
    "@apollo/client": "^3.0.0",
    "graphql": "^15.0.0"
  },
```

**Comment by ntziolis** [comment]
Can confirm that the following still appears with in `@apollo/client@3.3.11`.

```
Warning: .../node_modules/@apollo/client/utilities/observables/Observable.js depends on 'zen-observable'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
